# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65num2.proto\"5\n\x05test2\x12\x1e\n\ntest_enum2\x18\x01 \x02(\x0e\x32\n.TestEnum2\x12\x0c\n\x04\x63ode\x18\x02 \x02(\x0c*?\n\tTestEnum2\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03ONE\x10\x01\x12\x07\n\x03TWO\x10\x02\x12\t\n\x05THREE\x10\x03\x12\x08\n\x04\x46OUR\x10\x04')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enum2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTENUM2._serialized_start=70
  _TESTENUM2._serialized_end=133
  _TEST2._serialized_start=15
  _TEST2._serialized_end=68
# @@protoc_insertion_point(module_scope)
