# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65num1.proto\"|\n\x05test1\x12$\n\ntest_enum1\x18\x01 \x02(\x0e\x32\x10.test1.TestEnum1\x12\x0c\n\x04\x63ode\x18\x02 \x02(\x0c\"?\n\tTestEnum1\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03ONE\x10\x01\x12\x07\n\x03TWO\x10\x02\x12\t\n\x05THREE\x10\x03\x12\x08\n\x04\x46OUR\x10\x04')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enum1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEST1._serialized_start=15
  _TEST1._serialized_end=139
  _TEST1_TESTENUM1._serialized_start=76
  _TEST1_TESTENUM1._serialized_end=139
# @@protoc_insertion_point(module_scope)
